test1/demo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'groups#index'

   resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
end

  namespace :account do
    resources :groups
    resources :posts
end

end

test1/demo/app/models/group.rb
class Group < ActiveRecord::Base

	belongs_to :owner, :class_name => "User", :foreign_key => :user_id
	has_many :posts, :dependent => :destroy
	has_many :group_users
	has_many :members, :through => :group_users, :source => :user

	validates :title, :presence => true

	def editable_by?(user)
		user && user == owner
	end
end

test1/demo/app/models/group_user.rb
class GroupUser < ActiveRecord::Base
	belongs_to :user
	belongs_to :group
end

test1/demo/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :group, counter_cache: :posts_count
	validates :content,:presence =>true

	belongs_to :author, :class_name => "User", :foreign_key => :user_id
	def editable_by?(user)
		user && user == author
	end
end

test1/demo/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, :through => :group_users, :source => :group

  def join!(group)
  	participated_groups << group
  end

  def quit!(group)
  	participated_groups.delete(group)
  end

  def is_member_of?(group)
  	participated_groups.include?(group)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

test1/demo/app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
	before_action :authenticate_user!
	def index
		@groups = current_user.participated_groups
	end
end

test1/demo/app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
	before_action :authenticate_user!

  	def index
    	@posts = current_user.posts
  	end
end

test1/demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
end


end

test1/demo/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy] 
	def index
		@groups = Group.all
	end
	def show
		@group = Group.find(params[:id])
		@posts = @group.posts
	end
	def new
		@group = Group.new
	end
	def create
		@group = current_user.groups.build(group_params)

		if @group.save
			current_user.join!(@group)
			redirect_to groups_path
		else
			render :new
		end
	end

	def update
		@group = current_user.groups.find(params[:id])
		if @group.update(group_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end

	def edit
		@group = current_user.groups.find(params[:id])
	end

	def destroy
		@group = current_user.groups.find(params[:id])
		@group.destroy
		redirect_to groups_path
	end 

	def join
		@group = Group.find(params[:id])

		if !current_user.is_member_of?(@group)
			current_user.join!(@group)
		end
		redirect_to groups_path(@group)
	end

	def quit
		@group = Group.find(params[:id])
		if current_user.is_member_of?(@group)
			current_user.quit!(@group)
		end
		redirect_to groups_path(@group)
	end

	private
		def group_params
			params.require(:group).permit(:title, :description)
		end
end

test1/demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_group
	before_action :authenticate_user!
	before_action :member_required, :only => [:new, :create ]
	def new
		@post = @group.posts.build
	end

	def create
		@post = @group.posts.new(post_params)
		@post.author = current_user
		if@post.save
			redirect_to group_path(@group), :notice => '新增文章成功！'
		else
			render :new
		end
	end

	def edit
		@post = current_user.posts.find(params[:id])
	end

	def update
		@post = current_user.posts.find(params[:id])

		if@post.update(post_params)
			redirect_to group_path(@group)
		else
			render :edit
		end
	end
	def destroy
		@post = current_user.posts.find(params[:id])

		@post.destroy

		redirect_to group_path(@group), :alert => '文章已刪除'
	end

end
	private

	def post_params
		params.require(:post).permit(:content)
	end

	def find_group
		@group = Group.find(params[:group_id])
	end

	def member_required
		if !current_user.is_member_of?(@group)
			redirect_to group_path(@group)
		end
	end

test1/demo/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def hello
	end
end

test1/demo/app/helpers/account/groups_helper.rb
module Account::GroupsHelper
end

test1/demo/app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

test1/demo/app/helpers/application_helper.rb
module ApplicationHelper
end

test1/demo/app/helpers/groups_helper.rb
module GroupsHelper
end

test1/demo/app/helpers/posts_helper.rb
module PostsHelper
end

test1/demo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

test1/demo/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

test1/demo/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li> <%= link_to("註冊", new_user_registration_path) %> </li>
        <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.name %>  
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to("My Groups", account_groups_path) %></li> 
            <li> <%= link_to("My Posts", account_posts_path) %></li> 
            <li> <%= link_to("登出", destroy_user_session_path, 
                               :method => :delete ) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

test1/demo/app/views/groups/edit.html.erb
<div class="span12">
	<%= simple_form_for @group do |f| %>
		<%= f.input :title, :input_html => { :class => "input-xxlarge"} %>
		<%= f.input :description, :input_html => { :class => "input-xxlarge"} %>
		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>
	<% end %>
</div>

test1/demo/app/views/groups/index.html.erb
<div class="span12">
	<div class="group">
	<%= link_to("New group", new_group_path , :class => "btn btn-mini btn-primary pull-center" ) %>
	</div>
	<table class="table">
		<thead>
			<tr>
			<td> # </td>
			<td> Title </td>
			<td> Descroption </td>
			<td> Owner </td>
			</tr>
		</thead>

		<tbody>
			<% @groups.each do |group| %>
			<tr>
				<td> # </td>

				<td> 
					<% if current_user %> 
					<%= link_to(group.title, group_path(group)) %>
					<% else %> 
					<%= group.title %>
					<% end %>
				</td>
				<td> <%= group.description %> </td>
				<td> <%= group.owner.name %> </td>
				<td> 
					<% if current_user && group.editable_by?(current_user) %> 
					<%= link_to("Edit", edit_group_path(group), :class => "btn btn-mini btn-primary pull-center") %>
					<%= link_to("Delete", group_path(group), :class => "btn btn-mini btn-primary pull-center", :method => :delete, :confirm => "Are you sure?" ) %>
					<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

test1/demo/app/views/groups/new.html.erb
<div class="span12">
	<%= simple_form_for @group do |f| %>
		<%= f.input :title, :input_html => { :class => "input-xxlarge"} %>
		<%= f.input :description, :input_html => { :class => "input-xxlarge"} %>
		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>
	<% end %>
</div>

test1/demo/app/views/groups/show.html.erb
<div class="span12">
	<div class="group">
		<% if @group.editable_by?(current_user) %>
		<%= link_to("Edit", edit_group_path(@group) , :class => "btn btn-mini btn-primary pull-center")%>
		<% end %>
		<%= link_to("New Post", new_group_post_path(@group) , :class => "btn btn-mini btn-primary pull-center" )%>
		<%= link_to("Back", groups_path , :class => "btn btn-mini btn-primary pull-center" ) %>

		   <% if !current_user.nil? %>
      <% if current_user.is_member_of?(@group) %>
        <%= link_to("Quit Group", quit_group_path(@group), :method => :post, :class => "btn btn-info") %>
      <% else %>
        <%= link_to("Join Group", join_group_path(@group), :method => :post, :class => "btn btn-info") %>
      <% end %>
    <% end %>
	&nbsp;
</div>
<h2> <%= @group.title %> </h2>
<p> <%= @group.description %> </p>

<table class="table">

<tbody>
	<% @posts.each do |post| %>
	<tr>
		<td>
			<span class="author"><strong> Author : <%= post.author.name %></strong> </span>
		<p>
		<td> <%= post.content %> </td>
		</p>
		</td>
		<% if current_user && post.editable_by?(current_user) %>
		<td> <%= link_to("Edit", edit_group_post_path(post.group, post), :class =>"btn btn-mini")%>
			<%= link_to("Delete", group_post_path(post.group, post), :class => "btn btn-mini", :method => :delete, :confirm => "Are you sure?" ) %> 
		</td>
	</tr>
	<% end %>
	<% end %>
</tbody>
</table>
</div>

test1/demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <%= render "common/navbar" %>
	<%= yield %>
</div>
  <%= render "common/footer" %>

</body>
</html>

test1/demo/app/views/posts/edit.html.erb
<div class="span12">

	<%= simple_form_for [@group,@post] do |f| %>
		<%= f.input :content, :input_html => { :class => "input-xxlarge"} %>

		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>
	<% end %>

</div>

test1/demo/app/views/posts/new.html.erb
<div class="span12">
	<%= simple_form_for [@group,@post] do |f| %>
		<%= f.input :content, :input_html => { :class => "input-xxlarge"} %>
		<div class="form-actions">
			<%= f.submit "Submit", :disable_with => 'Submiting...', :class => "btn btn-primary" %>
		</div>
	<% end %>

</div>

test1/demo/app/views/welcome/hello.html.erb
Hello World!